import {useEffect,useState} from 'react';
import {GuestProfile,emptyGuest,validateGuest} from '../lib/guestModel';
import GuestProfileFields from './GuestProfileFields';
const endpoint=`${(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')}/functions/v1/guest-artists`;
export default function GuestArtistAdmin({accessCode,active}:{accessCode:string;active:boolean}){
 const [guests,setGuests]=useState<GuestProfile[]>([]),[profile,setProfile]=useState<GuestProfile|null>(null),[original,setOriginal]=useState('');
 const [photo,setPhoto]=useState(''),[removePhoto,setRemovePhoto]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('active');
 const [busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[invitation,setInvitation]=useState<{url:string;expires_at:string}|null>(null);
 const dirty=!!profile&&(JSON.stringify(profile)!==original||!!photo||removePhoto);
 const api=async(body:unknown)=>{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':accessCode},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to load guest artists.');return data;};
 const load=async()=>{setBusy(true);setError('');try{let all:GuestProfile[]=[];for(let offset=0;;offset+=500){const r=await api({action:'list',offset});all=all.concat(r.guests);if(r.guests.length<500)break;}setGuests(all);setLoaded(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{if(active&&!loaded)void load();},[active]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const open=async(id?:string)=>{if(dirty&&!window.confirm('Discard unsaved guest profile changes?'))return;setBusy(true);setError('');setMessage('');setInvitation(null);try{const p=id?(await api({action:'detail',id})).profile:emptyGuest();setProfile(p);setOriginal(JSON.stringify(p));setPhoto('');setRemovePhoto(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!profile)return;setError('');try{validateGuest(profile);}catch(err){setError((err as Error).message);return;}setBusy(true);try{const p=(await api({action:'save',profile,photo:photo||undefined,remove_photo:removePhoto})).profile;setProfile(p);setOriginal(JSON.stringify(p));setPhoto('');setRemovePhoto(false);setGuests(list=>[...list.filter(g=>g.id!==p.id),p].sort((a,b)=>a.display_name.localeCompare(b.display_name)));setMessage('Guest profile saved. Linked agenda names are updated.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
 const invite=async()=>{setBusy(true);setError('');try{setInvitation(await api({action:'invite',id:profile?.id}));setMessage('Private invitation created. Share it with this guest only; earlier links are revoked.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const revoke=async()=>{setBusy(true);setError('');try{await api({action:'revoke',id:profile?.id});setInvitation(null);setMessage('Unused invitation links revoked.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const visible=guests.filter(g=>(filter==='all'||g.status===filter)&&g.display_name.toLowerCase().includes(search.toLowerCase()));
 return <div><div className="mb-5 flex flex-wrap gap-3"><div className="rounded-xl bg-white p-4"><span className="text-sm text-slate-500">Active guest artists and instructors</span><strong className="ml-3 text-2xl">{loaded?guests.filter(g=>g.status==='active').length:'—'}</strong></div><button disabled={busy} onClick={load} className="rounded-xl border bg-white px-4 py-2">Refresh</button></div>
 {error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{message&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}
 <div className="grid items-start gap-5 xl:grid-cols-[300px_minmax(0,1fr)]"><section className="rounded-2xl bg-white p-5 shadow-sm" aria-label="Guest artist directory"><div className="flex items-center justify-between"><h2 className="font-semibold">Guest Artists ({visible.length})</h2><button disabled={busy} onClick={()=>open()} className="rounded-lg bg-rose-700 px-3 py-2 text-sm text-white">Add guest</button></div><label className="mt-4 block text-sm">Search guests<input className="mt-1 w-full rounded-lg border p-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="mt-3 block text-sm">Status filter<select className="mt-1 w-full rounded-lg border p-2" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All statuses</option></select></label><ul className="mt-4 space-y-1">{visible.map(g=><li key={g.id}><button disabled={busy} onClick={()=>open(g.id)} className={`w-full rounded-lg p-3 text-left ${profile?.id===g.id?'bg-rose-50':'hover:bg-slate-50'}`}><span className="block font-medium">{g.display_name}</span><span className="text-xs text-slate-500">{g.role==='instructor'?'Instructor':'Guest artist'}</span></button></li>)}</ul>{loaded&&!visible.length&&<p className="py-5 text-sm text-slate-500">No matching profiles.</p>}</section>
 {profile?<form onSubmit={save} className="min-w-0 space-y-6 rounded-2xl bg-white p-5 shadow-sm sm:p-7"><fieldset disabled={busy} className="min-w-0 space-y-6"><div><h2 className="font-serif text-2xl">{profile.id?profile.display_name:'New guest artist'}</h2><p className="mt-1 text-sm text-slate-500">Contact details, photos and bios are private to the studio. Names appear on linked recital agendas.</p></div><GuestProfileFields profile={profile} patch={p=>setProfile({...profile,...p})} photo={photo} onPhoto={p=>{setPhoto(p);setRemovePhoto(false);}} onRemovePhoto={()=>{setPhoto('');setRemovePhoto(true);setProfile({...profile,photo_url:'',photo_path:''});}} onError={setError}/><button disabled={busy||!dirty} className="rounded-xl bg-rose-700 px-5 py-3 font-semibold text-white disabled:opacity-50">Save guest profile</button>{dirty&&<span className="ml-3 text-sm text-amber-700">Unsaved changes</span>}
 {profile.id&&<section className="space-y-3 border-t pt-5"><h3 className="font-semibold">Invite this guest to complete their profile</h3><p className="text-sm text-slate-500">The private link expires after 30 days and can be submitted once. Creating a new link replaces earlier unused links. Save profile changes first.</p><div className="flex flex-wrap gap-3"><button disabled={busy||dirty} type="button" onClick={invite} className="rounded-lg border border-rose-700 px-4 py-2 text-rose-700 disabled:opacity-50">Create invitation link</button><button disabled={busy||dirty} type="button" onClick={revoke} className="rounded-lg border px-4 py-2 text-sm">Revoke unused links</button></div>{invitation&&<div className="rounded-xl bg-rose-50 p-4"><label className="text-sm">Private invitation link<input readOnly value={invitation.url} className="mt-2 w-full rounded-lg border bg-white p-2 text-sm" onFocus={e=>e.target.select()}/></label><p className="mt-2 text-xs">Expires {new Date(invitation.expires_at).toLocaleDateString()}</p><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(invitation.url);setMessage('Invitation link copied.');}catch{setMessage('Select and copy the invitation link above.');}}} className="mt-3 text-sm font-semibold text-rose-700">Copy invitation link</button></div>}</section>}</fieldset></form>:<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">Select a guest or instructor to edit their profile or create an invitation.</div>}</div></div>;
}
