import {GuestProfile} from '../lib/guestModel';
import {prepareGuestPhoto} from '../lib/guestPhoto';
const input='mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-base';
export default function GuestProfileFields({profile,patch,invited=false,photo,onPhoto,onRemovePhoto,onError}:{profile:GuestProfile;patch:(p:Partial<GuestProfile>)=>void;invited?:boolean;photo:string;onPhoto:(photo:string)=>void;onRemovePhoto:()=>void;onError:(message:string)=>void}){
 return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">
  <label className="text-sm sm:col-span-2">Full name<input required maxLength={160} className={input} value={profile.display_name} onChange={e=>patch({display_name:e.target.value})}/></label>
  <label className="text-sm">Contact person (optional)<input maxLength={160} className={input} value={profile.contact_name} onChange={e=>patch({contact_name:e.target.value})}/><span className="mt-1 block text-xs text-slate-500">Manager, parent or other contact, if different.</span></label>
  <label className="text-sm">Contact email<input required={invited} type="email" maxLength={254} className={input} value={profile.email} onChange={e=>patch({email:e.target.value})}/></label>
  <label className="text-sm">Phone number<input required={invited} type="tel" maxLength={50} placeholder="+1 425 555 0123" className={input} value={profile.phone} onChange={e=>patch({phone:e.target.value})}/></label>
  {!invited&&<><label className="text-sm">Profile type<select className={input} value={profile.role} onChange={e=>patch({role:e.target.value as GuestProfile['role']})}><option value="guest">Guest artist</option><option value="instructor">Instructor</option></select></label><label className="text-sm">Status<select className={input} value={profile.status} onChange={e=>patch({status:e.target.value as GuestProfile['status']})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></>}
 </div><label className="block text-sm">Short bio<textarea required={invited} maxLength={2000} rows={5} className={input} value={profile.bio} onChange={e=>patch({bio:e.target.value})}/><span className="text-xs text-slate-500">{profile.bio.length}/2000 characters</span></label>
 <div><label className="block text-sm">Profile photo (optional)<input type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full rounded-lg border p-3 text-sm" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{onPhoto(await prepareGuestPhoto(file));}catch(err){onError((err as Error).message);}e.target.value='';}}/></label><p className="mt-1 text-xs text-slate-500">JPG, PNG or WebP, up to 10 MB. We resize the photo for your profile.</p>
 {(photo||profile.photo_url)&&<div className="mt-3 flex items-end gap-4"><img src={photo?`data:image/webp;base64,${photo}`:profile.photo_url} alt="Profile preview" className="h-32 w-32 rounded-xl object-cover"/><button type="button" className="text-sm text-rose-700 underline" onClick={onRemovePhoto}>Remove photo</button></div>}</div></div>;
}
