import {useEffect,useState} from 'react';
import {GuestProfile,validateGuest} from '../lib/guestModel';
import GuestProfileFields from '../components/GuestProfileFields';
const endpoint=`${(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')}/functions/v1/guest-artists`;
export default function GuestInvitation(){
 const [token]=useState(()=>window.location.hash.slice(1));const [profile,setProfile]=useState<GuestProfile|null>(null),[photo,setPhoto]=useState(''),[removePhoto,setRemovePhoto]=useState(false),[authorized,setAuthorized]=useState(false);
 const [busy,setBusy]=useState(true),[error,setError]=useState(''),[done,setDone]=useState(false),[expires,setExpires]=useState('');
 const api=async(body:unknown)=>{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to save your profile.');return data;};
 const load=async()=>{setBusy(true);setError('');try{if(!/^[0-9a-f]{64}$/.test(token))throw Error('Use the private invitation link sent by Nrityangan. Contact the studio if you need a new link.');const r=await api({action:'invitation',token});setProfile(r.profile);setExpires(r.expires_at);setPhoto('');setRemovePhoto(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{validateGuest(profile,true);if(!authorized)throw Error('Confirm that you are authorized to submit this profile.');}catch(err){setError((err as Error).message);return;}setBusy(true);try{await api({action:'submit_invitation',token,profile,photo:photo||undefined,remove_photo:removePhoto,authorized});setDone(true);window.history.replaceState(null,'',window.location.pathname);}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
 return <main className="bg-rose-50 px-4 py-12 sm:py-16"><div className="mx-auto max-w-2xl rounded-2xl bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-semibold uppercase tracking-widest text-rose-700">Nrityangan Kathak Studio</p><h1 className="mt-3 font-serif text-3xl">Guest artist invitation</h1>
 {done?<div role="status" className="mt-6 rounded-xl bg-emerald-50 p-5"><h2 className="text-xl font-semibold">Thank you for sharing your profile</h2><p className="mt-2">Your details have been saved with the studio. Please contact Nrityangan if you need to make further changes.</p></div>:<><p className="mt-3 text-slate-600">We look forward to welcoming you. Please share your contact details, a photo and a short introduction. Your profile is stored privately with the studio; submitting this form does not publish your photo or bio.</p>{error&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{busy&&!profile&&<p role="status" className="mt-5">Loading invitation…</p>}{profile&&<form className="mt-7 space-y-5" onSubmit={submit}><fieldset disabled={busy} className="space-y-5"><GuestProfileFields invited profile={profile} patch={p=>setProfile({...profile,...p})} photo={photo} onPhoto={p=>{setPhoto(p);setRemovePhoto(false);}} onRemovePhoto={()=>{setPhoto('');setRemovePhoto(true);setProfile({...profile,photo_url:'',photo_path:''});}} onError={setError}/><label className="flex items-start gap-3 text-sm"><input required type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)} className="mt-1"/>I am the guest artist or am authorized to submit these details and this photo to Nrityangan Kathak Studio.</label><p className="text-xs text-slate-500">Your contact information is used to coordinate with you. For corrections or removal requests, call (425) 785-5217. This invitation expires {new Date(expires).toLocaleDateString()} and can be submitted once.</p><button disabled={busy} className="w-full rounded-xl bg-rose-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Submit guest profile'}</button></fieldset><button type="button" disabled={busy} onClick={()=>{if(window.confirm('Reload and discard your unsaved changes?'))void load();}} className="text-sm text-slate-500 underline">Reload profile</button></form>}</>}</div></main>;
}
