import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Camera, MapPin, Play } from 'lucide-react';
import recitals from '../content/recitals.json';
const Gallery = lazy(() => import('./Gallery'));
const RecitalPromo = lazy(() => import('../components/RecitalPromo'));
const RecitalArchive = lazy(() => import('../components/RecitalArchive'));
const Performances = lazy(() => import('../components/RecitalPerformances'));

export default function Recitals({ year }: { year?: string }) {
  const recital = recitals.find(item => item.year === year);
  const [tab, setTab] = useState<'photos' | 'performances'>('photos');
  useEffect(() => {
    const previous = document.title;
    document.title = `${recital ? `${recital.title} ${recital.year}` : year ? 'Recital not found' : 'Annual Recitals'} | Nrityangan Kathak`;
    const description = document.querySelector('meta[name="description"]');
    const canonical = document.querySelector('link[rel="canonical"]');
    const previousDescription = description?.getAttribute('content');
    const previousCanonical = canonical?.getAttribute('href');
    description?.setAttribute('content', recital?.description || 'Explore annual recitals, photo galleries and artist performances from Nrityangan Kathak Studio.');
    canonical?.setAttribute('href', `https://www.kathakseattle.com/recitals${recital ? `/${recital.year}` : ''}`);
    return () => {
      document.title = previous;
      if (previousDescription !== null && previousDescription !== undefined) description?.setAttribute('content', previousDescription);
      if (previousCanonical !== null && previousCanonical !== undefined) canonical?.setAttribute('href', previousCanonical);
    };
  }, [recital, year]);
  if (year && !recital) return <section className="mx-auto max-w-5xl px-6 py-24"><h1 className="font-serif text-4xl">Recital not found</h1><a href="/recitals" className="mt-6 inline-block text-rose-700 underline">Explore annual recitals</a></section>;
  if (!recital) return <div className="min-h-screen bg-stone-50">
    <header className="bg-[#321415] px-6 py-20 text-center text-white"><p className="text-sm uppercase tracking-[0.25em] text-amber-300">Nrityangan on stage</p><h1 className="mt-5 font-serif text-4xl sm:text-6xl">Annual Recitals</h1><p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-rose-100">A year of practice. An evening of joy. Explore the performances and memories of our Kathak community, one year at a time.</p></header>
    <section aria-label="Recitals by year" className="mx-auto max-w-6xl px-6 py-14"><div className="grid gap-8 md:grid-cols-2">{[...recitals].sort((a,b) => Number(b.year)-Number(a.year)).map(item => <a key={item.year} href={`/recitals/${item.year}`} className="group grid overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm sm:grid-cols-[2fr_3fr]"><div className="aspect-square overflow-hidden"><img src={item.thumbnail} alt={`${item.title} annual recital ${item.year}`} width="424" height="600" loading="lazy" decoding="async" className="h-full w-full object-cover object-top"/></div><div className="p-7"><span className="text-sm font-bold uppercase tracking-widest text-rose-700">Annual Recital · {item.year}</span><h2 className="mt-4 font-serif text-3xl">{item.title}</h2>{item.comingSoon && <span className="mt-3 inline-block rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-900">Coming Soon</span>}<p className="mt-3 font-medium text-slate-700"><time dateTime={item.date}>{item.dateLabel}</time></p><p className="mt-4 leading-relaxed text-slate-600">{item.description}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold text-rose-700">{item.comingSoon ? 'View recital details' : 'Explore the recital'} <ArrowRight size={18}/></span></div></a>)}</div></section>
  </div>;
  return <div className="bg-stone-50">
    <header className="bg-[#321415] text-white"><div className="mx-auto grid max-w-6xl items-center gap-10 px-6 py-12 md:grid-cols-[3fr_2fr]"><div><a href="/recitals" className="inline-flex items-center gap-2 text-sm text-rose-100"><ArrowLeft size={16}/> All recitals</a><p className="mt-9 text-sm uppercase tracking-[0.25em] text-amber-300">Annual Recital {recital.year}</p>{recital.comingSoon && <span className="mt-4 inline-block rounded-full bg-amber-200 px-4 py-1 text-sm font-semibold text-amber-950">Coming Soon</span>}<h1 className="mt-4 font-serif text-5xl sm:text-6xl">{recital.title}</h1><p className="mt-5 font-serif text-2xl text-amber-200">{recital.subtitle}</p><p className="mt-5 max-w-xl text-lg leading-relaxed text-rose-100">{recital.description}</p><p className="mt-6 flex items-center gap-2 text-amber-200"><CalendarDays size={18}/><time dateTime={recital.date}>{recital.dateLabel}</time></p>{recital.time && <p className="mt-2 text-rose-100">{recital.time}</p>}<p className="mt-4 flex items-center gap-2 text-rose-100"><MapPin size={18}/>{recital.venue}</p><ul className="mt-8 grid gap-3 text-sm text-rose-100">{recital.highlights.map(text => <li key={text}>✦ {text}</li>)}</ul></div><div className={recital.comingSoon ? "aspect-square overflow-hidden rounded-xl" : "overflow-hidden rounded-xl"}><img src={recital.poster} alt={`${recital.title} annual recital artwork`} width="1055" height="1491" decoding="async" className={recital.comingSoon ? "h-full w-full object-cover object-top" : "mx-auto max-h-[650px] w-auto max-w-full object-contain"}/></div></div></header>
    {recital.promo && <Suspense fallback={<p role="status" className="p-12">Loading promo...</p>}><RecitalPromo src={recital.promo.src} poster={recital.promo.poster} year={recital.year}/></Suspense>}
    {recital.archive ? <Suspense fallback={<p role="status" className="p-12">Loading recital memories...</p>}><RecitalArchive archive={recital.archive}/></Suspense> : <section className="mx-auto max-w-7xl px-6 py-12" aria-label="Recital memories"><div className="mb-9 flex flex-wrap items-end justify-between gap-6"><div><h2 className="font-serif text-3xl">{recital.comingSoon ? 'Coming Soon' : 'Relive the celebration'}</h2><p className="mt-3 text-slate-600">{recital.comingSoon ? 'Our 2026 recital gallery and artist performances will be shared here.' : 'Moments from the stage and the artists who made them special.'}</p></div>{!recital.comingSoon && <div role="group" aria-label="Choose recital content" className="flex rounded-full border bg-white p-1"><button aria-pressed={tab === 'photos'} onClick={() => setTab('photos')} className={`flex items-center gap-2 rounded-full px-5 py-3 ${tab === 'photos' ? 'bg-rose-700 text-white' : 'text-slate-600'}`}><Camera size={17}/>Photos</button><button aria-pressed={tab === 'performances'} onClick={() => setTab('performances')} className={`flex items-center gap-2 rounded-full px-5 py-3 ${tab === 'performances' ? 'bg-rose-700 text-white' : 'text-slate-600'}`}><Play size={17}/>Performances</button></div>}</div>
      {recital.comingSoon ? <div className="grid gap-6 sm:grid-cols-2"><div className="rounded-2xl border border-stone-200 bg-white p-8"><Camera className="text-rose-700"/><h3 className="mt-4 font-serif text-2xl">Photo Gallery</h3><p className="mt-3 font-semibold text-rose-700">Coming Soon</p></div><div className="rounded-2xl border border-stone-200 bg-white p-8"><Play className="text-rose-700"/><h3 className="mt-4 font-serif text-2xl">Artist Performances</h3><p className="mt-3 font-semibold text-rose-700">Coming Soon</p></div></div> : <Suspense fallback={<p role="status">Loading recital memories…</p>}>{tab === 'photos' ? recital.photoAlbums.length ? <Gallery key={recital.year} albumNames={recital.photoAlbums} embedded /> : <div className="rounded-2xl border border-stone-200 bg-white p-8"><Camera className="text-rose-700"/><h3 className="mt-4 font-serif text-2xl">Memories in the making</h3><p className="mt-3 text-slate-600">Photos from this recital will be shared here. Please check back for the gallery.</p></div> : <Performances key={recital.year} file={recital.performancesFile}/>}</Suspense>}
    </section>}
  </div>;
}
